name:

on:
  workflow_run:
    workflows: [Docker Tests]
    types: [completed]

jobs:

  on-success:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    # conserver les steps précedents

    - name: Checkout code for the update
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Update Deployment Image Tag  # Nom de l'étape dans le workflow GitHub Actions
      run: |  # Début de l'exécution d'un script shell
        sed -i "s|${{ secrets.DOCKER_USERNAME }}/projet-flask-v0.1:.*|${{ secrets.DOCKER_USERNAME }}/projet-flask-v0.1:${{ github.sha }}|g" ./deployment/flask.yaml
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -am "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push origin main

  on-failure:
    # conserver le code de ce job
